# Generated by Django 5.1.2 on 2024-10-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission_pannes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='date_signalement',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='etat',
        ),
        migrations.AlterField(
            model_name='panne',
            name='localisation',
            field=models.CharField(max_length=200),
        ),
    ]
