# Generated by Django 5.1.2 on 2024-10-12 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission_pannes', '0002_remove_panne_date_signalement_remove_panne_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='panne',
            name='localisation',
        ),
        migrations.AddField(
            model_name='panne',
            name='date_signalement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='status',
            field=models.CharField(default='Non traitée', max_length=50),
        ),
        migrations.AlterField(
            model_name='panne',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='panne',
            name='infrastructure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soumission_pannes.infrastructure'),
            preserve_default=False,
        ),
    ]
