# Generated by Django 5.1.2 on 2024-10-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission_pannes', '0003_infrastructure_remove_panne_localisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='soumission_pannes.infrastructure'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='status',
            field=models.CharField(choices=[('Non traitée', 'Non traitée'), ('En cours', 'En cours'), ('Résolue', 'Résolue')], default='Non traitée', max_length=50),
        ),
    ]
